/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "- Manage your save states. -": "- 管理你的保存状态。-",
    "- Operations halted. -": "- 行动停止。-",
    "- The Last Update (for now) -": "- 最后更新（目前）-",
    "- Tweak your preferences. -": "- 调整你的偏好。-",
    ". Auto-saving has been enabled. Check the console for more details, and consider sharing it with the developers on discord.": ".自动保存已启用。检查控制台了解更多详细信息，并考虑在discord上与开发者分享。",
    "▲ Select a loop from above ▲": "▲ 从上面选择一个循环 ▲",
    "Added more buildings": "添加了更多建筑物",
    "Added new building type - Influencer": "添加了新的建筑类型 - 影响者",
    "Added new buildings": "添加了新建筑物",
    "Added new objectives": "添加了新目标",
    "Added the meta game": "添加了元游戏",
    "Added transition animations between hub and game": "添加了集线器和游戏之间的过渡动​​画",
    "Adjusted enemies' health formula": "调整了敌人的生命值公式",
    "Allow the game to run as fast as possible. Not battery friendly.": "让游戏尽可能快地运行。不适合电池。",
    "ARCHIVE": "档案",
    "Attempted to assign \"\" to NaN": "尝试将 \"\" 分配给 NaN",
    "Automatically save the game every second or when the game is closed.": "每秒或游戏关闭时自动保存游戏。",
    "Autosave": "自动保存",
    "Back": "返回",
    "Behaviour": "行为",
    "Changed how game modes affect health": "改变了游戏模式影响健康的方式",
    "Close": "关闭",
    "Congratulations!": "恭喜！",
    "Continue": "继续",
    "Create Save": "创建保存",
    "Created some bugs to fix later": "创建了一些错误以便稍后修复",
    "Cycle": "循环",
    "Cycles reached": "已达到周期数",
    "default body": "默认主体",
    "DELOOPED": "开发循环",
    "Did everything": "做了一切",
    "energy": "能源",
    "Fix breaking error": "修复中断错误",
    "Forfeit and Return to Hub": "放弃并返回中心",
    "GAME OVER": "游戏结束",
    "Had some fun": "玩得很开心",
    "HP:": "生命值：",
    "Hub rewards:": "中心奖励：",
    "Ignore": "忽略",
    "Import Save": "导入保存",
    "NaN value detected!": "检测到 NaN 值！",
    "New Game": "新游戏",
    "Open Saves Manager": "打开存档管理器",
    "PAUSED": "暂停",
    "Relative lifetime": "相对寿命",
    "Removed everything": "删除了所有内容",
    "Replay": "重玩",
    "Restart": "重新开始",
    "Return to Hub": "返回中心",
    "SETTINGS": "设置",
    "Share": "分享",
    "Stress:": "压力：",
    "Style polishments": "风格修饰",
    "The cycle has been broken.": "循环已被打破。",
    "The Modding Tree": "模组树",
    "The Paper Pilot Community": "纸质试点社区",
    "This is the first release :D": "这是第一个版本：D",
    "Total resources gained:": "获得的总资源：",
    "Unthrottled": "无节制",
    "v0.1 Prototype Thing -": "v0.1 原型东西 -",
    "v0.2 Slightly Less Prototypey Thing -": "v0.2 稍微少一点的原型 -",
    "v0.2.1 Slightly Less Prototypey Thing -": "v0.2.1 稍微少一点的原型 -",
    "v0.3 Lesser Prototypey Thing -": "v0.3 较小的原型事物 -",
    "v0.4 this game isn't that great tbh -": "v0.4 说实话这个游戏不太好 -",
    "v0.5": "v0.5",
    "v0.5 The Last Update (for now) -": "v0.5 最后更新（目前）-",
    "XP": "经验值",
    "You've beaten Delooped v0.5: The Last Update (for now)": "您已通关 Delooped v0.5：最后更新（目前）",
    "Beamer": "投影仪",
    "Damage": "伤害",
    "Energy": "能源",
    "Interval": "间隔",
    "Level": "等级",
    "No building": "没有建筑物",
    "Select a building to build →": "选择要建造的建筑物→",
    "Sell for": "售价为",
    "▲ Select a loop to build ▲": "▲ 选择要构建的循环 ▲",
    "Amount": "数量",
    "Energizer": "劲量",
    "Beams one random enemy on the loop it's on once every a certain amount of time.": "每隔一定时间向循环中的一名随机敌人发射一次光束。",
    "BUILDING COST:": "建筑成本：",
    "DAMAGER": "破坏者",
    "Sell cooldown": "出售冷却时间",
    "STARTING SPECS:": "起始规格：",
    "<strong>We're sorry but Profectus doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>": "<strong>很抱歉，如果没有启用 JavaScript，Profectus 将无法正常工作。请启用它才能继续。</strong>",
    "Apply the \"Freezing\" effect to enemies when one moves out of the loop it's on. Freezed enemies' speed are halved. If the enemy has the \"Blazing\" effect, removes it.": "当敌人走出循环时，对敌人施加“冰冻”效果。被冰冻的敌人速度减半。如果敌人有“炽热”效果，则将其移除。",
    "Deal damage per second to all enemies on the loop it's on.": "每秒对循环中的所有敌人造成伤害。",
    "Duration": "持续时间",
    "EFFECTOR": "效应器",
    "Freezer": "冰箱",
    "GENERATOR": "发电机",
    "Infuse enemies with Energy while they are on the loop it's on, resulting in them dropping more Energy when defeated. Scales with base enemy speed.": "当敌人处于循环状态时，为他们注入能源，导致他们在被击败时掉落更多能源。与敌人的基本速度成比例。",
    "Plasma": "等离子",
    "Copied to clipboard": "已复制到剪切板",
    "- Do tasks. Reap rewards. -": "- 做任务，获得奖励。-",
    "All-Seeing": "全视",
    "Anxiety": "焦虑",
    "Buy 3 Researches.": "购买 3 个研究。",
    "Complete 20 Objectives.": "完成 20 个目标。",
    "Costs:": "成本:",
    "First Cycle": "第一个循环",
    "Gain a total of 500 XP.": "总共获得 500 XP。",
    "Have a 300 seconds long game.": "进行 300 秒的游戏。",
    "Is This P2W?": "这是P2W吗？",
    "Knowledged Looper": "知识丰富的循环者",
    "Look how much you've grown!": "看看你成长了多少！",
    "Marathoner": "马拉松选手",
    "Normal": "正常",
    "Not Really a Fair Game": "并不是真正的公平游戏",
    "OBJECTIVES": "目标",
    "Open 10 💊.": "打开10💊。",
    "Power Player": "强力玩家",
    "Reach a best total Energy of 10,000.": "最佳总能量达到 10,000。",
    "Reach a best total Information of 1,000.": "信息总数最好达到 1,000。",
    "Second Cycle": "第二个循环",
    "Special": "特殊",
    "Stucked": "卡住",
    "Third Cycle": "第三循环",
    "Unlock Objectives.": "解锁目标。",
    "Very Creative Objective": "非常有创意的目标",
    "xp": "经验值",
    "Quality": "质量",
    "Aqua": "水族",
    "High": "高",
    "How much should the game trade performance for visual quality.": "游戏应该在多大程度上牺牲性能来换取视觉质量。",
    "Low": "低",
    "Medium": "中",
    "Nordic": "北欧风格",
    "Paper": "纸",
    "- Replay. Research. Repeat. -": "- 重播、研究、重复。-",
    "Better Funding": "更好的资金",
    "Bigger Inventory": "库存更大",
    "Decommission Machine": "退役机",
    "Increase the maximum amount of buildings you can equip by 1.": "将您可以装备的建筑物的最大数量增加 1。",
    "Increase the starting Energy budget by 25.": "将起始能源预算增加 25。",
    "Is disabled on certain game modes.": "在某些游戏模式下被禁用。",
    "LABORATORY": "实验室",
    "pausing": "暂停",
    "Reduce the selling cooldown by 5 seconds.": "减少出售冷却时间 5 秒。",
    "s / 10s": " /10秒",
    "Speed Manipulation": "速度操控",
    "Unlock": "开锁",
    "Unlock Research.": "解锁研究。",
    "xp.": "经验值。",
    "Deal 727 damage to ALL enemies on the board, but only when your Energy hits exactly 727. Removes itself on the board when triggered or 72.7 seconds after it is placed and will not reverse its cost scaling when it does so. Is not affected by enemy effects and influencers.": "对界面上的所有敌人造成 727 点伤害，但仅当您的能源刚好达到 727 点时。触发时或放置后 72.7 秒将其自身从界面上移除，并且在这样做时不会逆转其成本缩放比例。不受敌人影响效果和影响者。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Last played ": "上次游戏时间 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " buildings unlocked": " 建筑已解锁",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^TPS: ([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Reach Cycle (.+) in Boosted mode.$/, '在提升模式下达到第 $1 轮循环。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)rad$/, '$1 弧度'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Energy$/, '$1 能源'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)\/hit$/, '$1\/命中'],
    [/^([\d\.,]+)\/rad$/, '$1\/弧度'],
    [/^Set to ([\d\.,]+)$/, '设置为 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);